App\Entity\Network\Service:
    type: entity
    table: network.service
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        isActive:
            type: boolean
            nullable: false
            options:
                default: true
            column: is_active
        recordingDate:
            type: datetime
            nullable: false
            options:
                default: now()
            column: recording_date
        removalDate:
            type: datetime
            nullable: true
            column: removal_date
        nickname:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
    lifecycleCallbacks: {  }
