#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authorize:
    prefix: /auth
    resource: './routes/authorize.yaml'
users:
    prefix: /users
    resource: './routes/users.yaml'
service:
    prefix: /service
    resource: './routes/service.yaml'