#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authorize:
    prefix: /auth
    resource: './routes/authorize.yaml'
users:
    prefix: /users
    resource: './routes/users.yaml'
service:
    prefix: /service
    resource: './routes/service.yaml'
pop:
    prefix: /pop
    resource: './routes/pop.yaml'
switch_model:
    prefix: /switchmodel
    resource: './routes/switchmodel.yaml'
